import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair O_1 = dir(110);
pair O_2 = dir(210);
pair O_3 = dir(330);
pair X = (O_2+2*O_3)/3;
pair Y = (2*O_2+O_3)/3;
pair Z = (O_1+2*O_3)/3;
pair A = IP(CP(O_2,X),CP(O_3,Y),1);
pair B = IP(CP(O_2,X),CP(O_3,Y),0);
pair C = IP(CP(O_2,X),CP(O_1,Z),1);
pair D = IP(CP(O_2,X),CP(O_1,Z),0);
pair E = IP(CP(O_1,Z),CP(O_3,Y),1);
pair F = IP(CP(O_1,Z),CP(O_3,Y),0);

draw(CP(O_1,Z));
draw(CP(O_2,X));
draw(CP(O_3,Y));
draw(A--B);
draw(C--D);
draw(E--F);

dot("$O_1$", O_1, dir(O_1));
dot("$O_2$", O_2, dir(O_2));
dot("$O_3$", O_3, dir(O_3));

/* Source generated by TSQX */