import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair O_1 = dir(210);
pair O_3 = dir(330);
pair O_2 = (O_1 + O_3)/2;
real X = 2;
real Y = 2;
real Z = 2;
pair A = IP(CR(O_2,X),CR(O_3,Y),1);
pair B = IP(CR(O_2,X),CR(O_3,Y),0);
pair C = IP(CR(O_2,X),CR(O_1,Z),1);
pair D = IP(CR(O_2,X),CR(O_1,Z),0);
pair E = IP(CR(O_1,Z),CR(O_3,Y),1);
pair F = IP(CR(O_1,Z),CR(O_3,Y),0);

draw(CR(O_1,Z));
draw(CR(O_2,X));
draw(CR(O_3,Y));
draw(A--B);
draw(C--D);
draw(E--F);

dot("$O_1$", O_1, dir(O_1));
dot("$O_2$", O_2, dir(O_2));
dot("$O_3$", O_3, dir(O_3));

/* Source generated by TSQX */