import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair E = dir(80);
pair C = dir(45);
pair F = dir(-30);
pair B = dir(260);
pair D = dir(170);
pair A = dir(135);
pair X = IP(A--B, D--E);
pair Y = IP(B--C, E--F);
pair Z = IP(C--D, F--A);

draw(circumcircle(A, B, C));
draw(A--B--C--D--E--F--A);
draw(X--Y--Z);
draw(A--B--X--A, dotted);
draw(D--E--X--D, dotted);
draw(B--C--Y--B, dotted);
draw(E--F--Y--E, dotted);
draw(C--D--Z--C, dotted);
draw(F--A--Z--F, dotted);

dot("$A$", A, dir(A));
dot("$B$", B, dir(B));
dot("$C$", C, dir(C));
dot("$D$", D, dir(D));
dot("$E$", E, dir(E));
dot("$F$", F, dir(F));
dot(X);
dot(Y);
dot(Z);

/* Source generated by TSQX */
