import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair B = dir(75);
pair A = dir(50);
pair F = dir(10);
pair E = dir(260);
pair D = dir(170);
pair C = dir(135);
pair X = IP(Line(A,B,100), Line(D,E,100));
pair Y = IP(Line(B,C,100), Line(E,F,100));
pair Z = IP(Line(C,D,100), Line(F,A,100));

draw(circumcircle(A, B, C));
draw(A--B--C--D--E--F--A);
draw(X--Y--Z);
draw(A--B--X--A, dotted);
draw(D--E--X--D, dotted);
draw(B--C--Y--B, dotted);
draw(E--F--Y--E, dotted);
draw(C--D--Z--C, dotted);
draw(F--A--Z--F, dotted);

dot("$A$", A, dir(A));
dot("$B$", B, dir(B));
dot("$C$", C, dir(C));
dot("$D$", D, dir(D));
dot("$E$", E, dir(E));
dot("$F$", F, dir(F));
dot(X);
dot(Y);
dot(Z);

/* Source generated by TSQX */