import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair A = dir(15);
pair B = dir(-5);
pair C = dir(45);

draw(circumcircle(A, B, C));
draw(Line(A,B,5));

dot("$A$", A, dir(A));
dot("$B$", B, dir(B));

/* Source generated by TSQX */
