import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair A = dir(15);
pair B = dir(14.9);
pair C = dir(45);

draw(circumcircle(A, B, C));
draw(Line(A,B,999));

dot("$A$", A, dir(A));

/* Source generated by TSQX */
