import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair P = (-0.9,1.5);
pair Q = (-3,-0.5);
pair A = tangent(P, origin, 1, 1);
pair C = tangent(P, origin, 1, 2);
pair B = tangent(Q, origin, 1, 1);
pair D = tangent(Q, origin, 1, 2);
pair R = extension(A,B,C,D);
pair S = extension(A,D,B,C);

draw(unitcircle);
draw(A--B--C--D--A);
draw(A--P--C);
draw(B--Q--D);
draw(A--B--R--A);
draw(C--D--R--C);
draw(A--D--S--A);
draw(B--C--S--B);
draw(P--Q--R--S, dashed);

dot("$O$", origin);
dot("$P$", P, dir(P));
dot("$Q$", Q, dir(Q));
dot("$A$", A, dir(A));
dot("$C$", C, dir(C));
dot("$B$", B, dir(B));
dot("$D$", D, dir(D));
dot("$R$", R, dir(R));
dot("$S$", S, dir(S));

/* Source generated by TSQX */
