import olympiad;
import cse5;
size(8cm);
defaultpen(fontsize(15pt));
settings.outformat="pdf";
pair A = dir(180);
pair B = dir(0);
pair C = dir(30);
pair D = 2*C-A;
pair E = tangent(D,origin,1,2);
pair G = dir(90);
pair F = extension(A, G, B, E);
pair Gp = dir(-90);

draw(circumcircle(A, B, C));
draw(A--B);
draw(A--D);
draw(E--F);
draw(D--E);
draw(A--F);
draw(Line(D,F,0.7,0));
draw(Gp--F, dashed);

dot("$A$", A, dir(A));
dot("$B$", B, dir(B));
dot("$C$", C, dir(C));
dot("$D$", D, dir(D));
dot("$E$", E, dir(E));
dot("$G$", G, dir(G));
dot("$F$", F, dir(F));
dot("$G'$", Gp, dir(Gp));

/* Source generated by TSQX */
